#!/usr/bin/perl
import com.cloudbees.groovy.cps.NonCPS

String packages_path = "/opt/wshop/wshop-0.0.1/images"
String shell_path = "/opt/wshop/wshop-0.0.1/bin"
@NonCPS
def getBuildUser() {
    return currentBuild.rawBuild.getCause(Cause.UserIdCause).getUserId()
}

pipeline {
    agent any
    parameters {
        choice(name: "ENV", choices: ["prod"], description: "请选择升级环境名，默认为 prod")
        choice(name: "MODULE", choices: ["wshop-core"], description: "请选择要升级的模块")
        string(name: "BRANCH", defaultValue: "master", description: "请填写升级分支名, 默认为 master", trim: true)
        string(name: "VERSION", description: "请填写版本，X.Y.Z", trim: true)
    }
    options {
        timeout(time: 100, unit: "MINUTES")
    }
    stages {
        stage("Entering directory") {
            steps {
                script {
                    dir("jenkins-workspace/deploy-backend") {
                        stage("Create build directory") {
                            if (params.ENV.equals("prod")) {
                                remotes = [
                                        [name: "test", host: "172.24.3.82", port: 3222, user: "lowcode", allowAnyHosts: true]
                                ]
                            }
                            else {
                                error "Unknown ${ENV}!"
                            }
                            sh "mkdir wshop-core || true"
                        }
                        stage("Checkout service") {
                            checkout([$class: "GitSCM", branches: [[name: "*/${BRANCH}"]], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: "623294f4-b267-4ddf-a76a-831c04951e43", url: "https://github.com/heshuxing/wshop-service.git"]]])
                        }
                    }
                    dir("jenkins-workspace/deploy-backend/wshop-core") {
                        stage("mvn package") {
                            if (params.MODULE.equals("wshop-core")) {
                                sh "mvn clean package || exit 1"
                            }
                            else {
                                error "Unknow ${MODULE}"
                            }
                        }
                        stage("Replace Dockerfile") {
                            sh "echo ${VERSION}"
                            writeFile encoding: 'UTF-8', file: 'Dockerfile', text: """
                                FROM 172.18.1.22/lowcode/alpine-oraclejre8:8.202.08-slim
                                ADD ./target/wshop-core-${VERSION}.jar /opt/wshop
                                ENTRYPOINT ["java", "-jar","/opt/wshop"]
                            """
                        }
                        stage("Docker build && image") {
                            sh "docker build -t wshop-core:${VERSION} ."
                            sh "docker image save wshop-core:${VERSION} | gzip > wshop-core-${VERSION}.tar.gz"
                        }
                    }
                }
            }
        }
    }
}